In [1]:
import fastf1 as ff1
from fastf1 import plotting
from matplotlib import pyplot as plt
from matplotlib.pyplot import figure
import numpy as np
import pandas as pd

In [13]:
session = ff1.get_session(2020, 1, 'R')
session.load()

core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '99'
core        WARNING 	Driver  8: Lap timing integrity check failed for 1 lap(s)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['77', '16', '4', '44', '55', '11', '10', '31', '99', '5', '6', '26', '23', '7', '63', '8', '20', '18', '3', '33']

In [8]:
pd.DataFrame(session.session_info)

,Meeting,SessionStatus,ArchiveStatus,Key,Type,Name,StartDate,EndDate,GmtOffset,Path
Key,1279,Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
Name,Australian Grand Prix,Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
OfficialName,FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ...,Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
Location,Melbourne,Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
Number,1,Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
Country,"{'Key': 5, 'Code': 'AUS', 'Name': 'Australia'}",Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
Circuit,"{'Key': 10, 'ShortName': 'Melbourne'}",Inactive,NaN,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...
Status,NaN,Inactive,Generating,11234,Race,Race,2026-03-08 15:00:00,2026-03-08 17:00:00,0 days 11:00:00,2026/2026-03-08_Australian_Grand_Prix/2026-03-...

In [11]:
pd.DataFrame(session.weather_data)

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:13.466000,23.1,55.8,1013.7,False,36.2,114,1.8
1,0 days 00:01:13.482000,23.2,55.1,1013.6,False,35.9,110,3.0
2,0 days 00:02:13.483000,23.2,55.2,1013.6,False,35.6,115,3.2
3,0 days 00:03:13.485000,23.1,55.7,1013.7,False,35.7,104,3.4
4,0 days 00:04:13.518000,23.1,55.8,1013.8,False,35.8,108,3.1
...,...,...,...,...,...,...,...,...
143,0 days 02:23:14.291000,25.2,51.9,1011.5,False,34.6,127,3.7
144,0 days 02:24:14.277000,25.2,52.0,1011.5,False,34.4,105,2.9
145,0 days 02:25:14.290000,25.1,51.7,1011.5,False,34.5,103,2.9
146,0 days 02:26:14.290000,25.0,52.2,1011.5,False,34.3,114,2.5
147,0 days 02:27:14.318000,25.0,52.7,1011.5,False,34.5,117,1.9

In [12]:
pd.DataFrame(session.race_control_messages)

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2026-03-08 03:08:08,Other,PINK HEAD PADDING MATERIAL MUST BE USED,None,None,None,NaN,None,0
1,2026-03-08 03:20:00,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
2,2026-03-08 03:21:22,Flag,DOUBLE YELLOW IN TRACK SECTOR 6,None,DOUBLE YELLOW,Sector,6.0,None,1
3,2026-03-08 03:21:25,Flag,CLEAR IN TRACK SECTOR 6,None,CLEAR,Sector,6.0,None,1
4,2026-03-08 03:21:26,Flag,YELLOW IN TRACK SECTOR 7,None,YELLOW,Sector,7.0,None,1
...,...,...,...,...,...,...,...,...,...
162,2026-03-08 05:26:19,Flag,WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 16:2...,None,BLUE,Driver,NaN,11,58
163,2026-03-08 05:26:33,Flag,CHEQUERED FLAG,None,CHEQUERED,Track,NaN,None,58
164,2026-03-08 05:29:56,Other,ALL PASS HOLDERS MAY ACCESS THE PIT LANE,None,None,None,NaN,None,58
165,2026-03-08 05:32:13,Flag,DOUBLE YELLOW IN TRACK SECTOR 19,None,DOUBLE YELLOW,Sector,19.0,None,58
166,2026-03-08 05:33:37,Flag,CLEAR IN TRACK SECTOR 19,None,CLEAR,Sector,19.0,None,58

In [ ]:
import json
pd.json_normalize(session.car_data, depth)

In [ ]:
session = ff1.get_session(2026, 4, 'R')
session.load()
fastest_lap = session.laps.pick_fastest()

# use padding so that there are values outside of the desired range for accurate interpolation later
car_data = fastest_lap.get_car_data(pad=1, pad_side='both')
pos_data = fastest_lap.get_pos_data(pad=1, pad_side='both')

# do calculations here
# ...
# ...

merged_data = car_data.merge_channels(pos_data)

# slice again to remove the padding and interpolate the exact first and last value
merged_data = merged_data.slice_by_lap(fastest_lap, interpolate_edges=True)

In [ ]:
merged_data

In [ ]:
import matplotlib.pyplot as plt
plt.hist(x=df['DRS'], y=df['count'])
df.info()

In [ ]:
df = pd.DataFrame(merged_data['DRS'].value_counts()).reset_index()

In [ ]:
df.shape

In [ ]:
df